"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.apiRouter = void 0;
const express_1 = require("express");
const admin_routes_1 = __importDefault(require("../modules/admin/admin.routes"));
const attendance_routes_1 = require("../modules/attendance/attendance.routes");
const audit_routes_1 = require("../modules/audit/audit.routes");
const auth_routes_1 = require("../modules/auth/auth.routes");
const books_routes_1 = require("../modules/books/books.routes");
const branches_routes_1 = require("../modules/branches/branches.routes");
const classes_routes_1 = require("../modules/classes/classes.routes");
const courses_routes_1 = require("../modules/courses/courses.routes");
const curriculum_routes_1 = require("../modules/curriculum/curriculum.routes");
const dashboard_routes_1 = require("../modules/dashboard/dashboard.routes");
const exams_routes_1 = require("../modules/exams/exams.routes");
const expenses_routes_1 = require("../modules/expenses/expenses.routes");
const fees_routes_1 = require("../modules/fees/fees.routes");
const families_routes_1 = require("../modules/families/families.routes");
const finance_routes_1 = require("../modules/finance/finance.routes");
const salaries_routes_1 = require("../modules/salaries/salaries.routes");
const language_settings_routes_1 = require("../modules/language-settings/language-settings.routes");
const notifications_routes_1 = require("../modules/notifications/notifications.routes");
const payments_routes_1 = require("../modules/payments/payments.routes");
const permissions_routes_1 = require("../modules/permissions/permissions.routes");
const reports_routes_1 = require("../modules/reports/reports.routes");
const results_routes_1 = require("../modules/results/results.routes");
const roles_routes_1 = require("../modules/roles/roles.routes");
const payroll_routes_1 = require("../modules/payroll/payroll.routes");
const employee_tax_routes_1 = require("../modules/payroll/employee-tax.routes");
const students_routes_1 = require("../modules/students/students.routes");
const student_messages_routes_1 = require("../modules/student-messages/student-messages.routes");
const messages_routes_1 = require("../modules/messages/messages.routes");
const subjects_routes_1 = require("../modules/subjects/subjects.routes");
const teachers_routes_1 = require("../modules/teachers/teachers.routes");
const timetable_routes_1 = require("../modules/timetable/timetable.routes");
const users_routes_1 = require("../modules/users/users.routes");
const uploads_routes_1 = require("../modules/uploads/uploads.routes");
const academy_financial_report_routes_1 = require("../modules/academy-financial-report/academy-financial-report.routes");
const search_routes_1 = require("../modules/search/search.routes");
const ai_results_routes_1 = require("../modules/ai-results/ai-results.routes");
const ai_assistant_routes_1 = require("../modules/ai-assistant/ai-assistant.routes");
const observability_routes_1 = require("../modules/observability/observability.routes");
const mobile_routes_1 = require("../modules/mobile/mobile.routes");
exports.apiRouter = (0, express_1.Router)();
exports.apiRouter.use(observability_routes_1.observabilityRouter);
exports.apiRouter.use('/mobile', mobile_routes_1.mobileRouter);
exports.apiRouter.use('/auth', auth_routes_1.authRouter);
exports.apiRouter.use('/uploads', uploads_routes_1.uploadsRouter);
exports.apiRouter.use('/users', users_routes_1.userRouter);
exports.apiRouter.use('/branches', branches_routes_1.branchRouter);
exports.apiRouter.use('/students', students_routes_1.studentRouter);
exports.apiRouter.use('/messages', messages_routes_1.messagesRouter);
exports.apiRouter.use('/student-messages', student_messages_routes_1.studentMessagesRouter);
exports.apiRouter.use('/teachers', teachers_routes_1.teacherRouter);
exports.apiRouter.use('/classes', classes_routes_1.classRouter);
exports.apiRouter.use('/timetable', timetable_routes_1.timetableRouter);
exports.apiRouter.use('/courses', courses_routes_1.courseRouter);
exports.apiRouter.use('/curriculum', curriculum_routes_1.curriculumRouter);
exports.apiRouter.use('/subjects', subjects_routes_1.subjectRouter);
exports.apiRouter.use('/attendance', attendance_routes_1.attendanceRouter);
exports.apiRouter.use('/exams', exams_routes_1.examRouter);
exports.apiRouter.use('/results', results_routes_1.resultRouter);
exports.apiRouter.use('/payments', payments_routes_1.paymentRouter);
exports.apiRouter.use('/fees', fees_routes_1.feeRouter);
exports.apiRouter.use('/finance', finance_routes_1.financeRouter);
exports.apiRouter.use('/salaries', salaries_routes_1.salariesRouter);
exports.apiRouter.use('/expenses', expenses_routes_1.expenseRouter);
exports.apiRouter.use('/families', families_routes_1.familyRouter);
exports.apiRouter.use('/books', books_routes_1.bookRouter);
exports.apiRouter.use('/audit', audit_routes_1.auditRouter);
exports.apiRouter.use('/notifications', notifications_routes_1.notificationRouter);
exports.apiRouter.use('/roles', roles_routes_1.roleRouter);
exports.apiRouter.use('/payroll', payroll_routes_1.payrollRouter);
exports.apiRouter.use('/employee-tax', employee_tax_routes_1.employeeTaxRouter);
exports.apiRouter.use('/permissions', permissions_routes_1.permissionsRouter);
exports.apiRouter.use('/dashboard', dashboard_routes_1.dashboardRouter);
exports.apiRouter.use('/reports', reports_routes_1.reportRouter);
exports.apiRouter.use('/language-settings', language_settings_routes_1.languageSettingRouter);
exports.apiRouter.use('/admin', admin_routes_1.default);
exports.apiRouter.use('/academy-financial-report', academy_financial_report_routes_1.academyFinancialReportRouter);
exports.apiRouter.use('/search', search_routes_1.searchRouter);
exports.apiRouter.use('/ai-results', ai_results_routes_1.aiResultsRouter);
exports.apiRouter.use('/ai-assistant', ai_assistant_routes_1.aiAssistantRouter);
