import { Router } from 'express';
import adminRouter from '../modules/admin/admin.routes';
import { attendanceRouter } from '../modules/attendance/attendance.routes';
import { auditRouter } from '../modules/audit/audit.routes';
import { authRouter } from '../modules/auth/auth.routes';
import { bookRouter } from '../modules/books/books.routes';
import { branchRouter } from '../modules/branches/branches.routes';
import { classRouter } from '../modules/classes/classes.routes';
import { contactSettingsAdminRouter, contactSettingsPublicRouter } from '../modules/contact-settings/contact-settings.routes';
import { courseRouter } from '../modules/courses/courses.routes';
import { curriculumRouter } from '../modules/curriculum/curriculum.routes';
import { dashboardRouter } from '../modules/dashboard/dashboard.routes';
import { examRouter } from '../modules/exams/exams.routes';
import { expenseRouter } from '../modules/expenses/expenses.routes';
import { feeRouter } from '../modules/fees/fees.routes';
import { familyRouter } from '../modules/families/families.routes';
import { faqAdminRouter, faqPublicRouter } from '../modules/faqs/faqs.routes';
import { legalDocumentsAdminRouter, legalDocumentsPublicRouter } from '../modules/legal-documents/legal-documents.routes';
import { financeRouter } from '../modules/finance/finance.routes';
import { salariesRouter } from '../modules/salaries/salaries.routes';
import { languageSettingRouter } from '../modules/language-settings/language-settings.routes';
import { notificationRouter } from '../modules/notifications/notifications.routes';
import { publicAnnouncementsRouter } from '../modules/notifications/public-announcements.routes';
import { paymentRouter } from '../modules/payments/payments.routes';
import { permissionsRouter } from '../modules/permissions/permissions.routes';
import { reportRouter } from '../modules/reports/reports.routes';
import { resultRouter } from '../modules/results/results.routes';
import { roleRouter } from '../modules/roles/roles.routes';
import { payrollRouter } from '../modules/payroll/payroll.routes';
import { employeeTaxRouter } from '../modules/payroll/employee-tax.routes';
import { studentRouter } from '../modules/students/students.routes';
import { studentMessagesRouter } from '../modules/student-messages/student-messages.routes';
import { messagesRouter } from '../modules/messages/messages.routes';
import { subjectRouter } from '../modules/subjects/subjects.routes';
import { teacherRouter } from '../modules/teachers/teachers.routes';
import { timetableRouter } from '../modules/timetable/timetable.routes';
import { userRouter } from '../modules/users/users.routes';
import { uploadsRouter } from '../modules/uploads/uploads.routes';
import { academyFinancialReportRouter } from '../modules/academy-financial-report/academy-financial-report.routes';
import { searchRouter } from '../modules/search/search.routes';
import { aiResultsRouter } from '../modules/ai-results/ai-results.routes';
import { aiAssistantRouter } from '../modules/ai-assistant/ai-assistant.routes';
import { observabilityRouter } from '../modules/observability/observability.routes';
import { mobileRouter } from '../modules/mobile/mobile.routes';

export const apiRouter = Router();

apiRouter.use(observabilityRouter);
apiRouter.use('/mobile', mobileRouter);

apiRouter.use('/auth', authRouter);
apiRouter.use('/public/faqs', faqPublicRouter);
apiRouter.use('/public/contact-settings', contactSettingsPublicRouter);
apiRouter.use('/public/legal-documents', legalDocumentsPublicRouter);
apiRouter.use('/public/announcements', publicAnnouncementsRouter);
apiRouter.use('/faqs', faqAdminRouter);
apiRouter.use('/contact-settings', contactSettingsAdminRouter);
apiRouter.use('/legal-documents', legalDocumentsAdminRouter);
apiRouter.use('/uploads', uploadsRouter);
apiRouter.use('/users', userRouter);
apiRouter.use('/branches', branchRouter);
apiRouter.use('/students', studentRouter);
apiRouter.use('/messages', messagesRouter);
apiRouter.use('/student-messages', studentMessagesRouter);
apiRouter.use('/teachers', teacherRouter);
apiRouter.use('/classes', classRouter);
apiRouter.use('/timetable', timetableRouter);
apiRouter.use('/courses', courseRouter);
apiRouter.use('/curriculum', curriculumRouter);
apiRouter.use('/subjects', subjectRouter);
apiRouter.use('/attendance', attendanceRouter);
apiRouter.use('/exams', examRouter);
apiRouter.use('/results', resultRouter);
apiRouter.use('/payments', paymentRouter);
apiRouter.use('/fees', feeRouter);
apiRouter.use('/finance', financeRouter);
apiRouter.use('/salaries', salariesRouter);
apiRouter.use('/expenses', expenseRouter);
apiRouter.use('/families', familyRouter);
apiRouter.use('/books', bookRouter);
apiRouter.use('/audit', auditRouter);
apiRouter.use('/notifications', notificationRouter);
apiRouter.use('/roles', roleRouter);
apiRouter.use('/payroll', payrollRouter);
apiRouter.use('/employee-tax', employeeTaxRouter);
apiRouter.use('/permissions', permissionsRouter);
apiRouter.use('/dashboard', dashboardRouter);
apiRouter.use('/reports', reportRouter);
apiRouter.use('/language-settings', languageSettingRouter);
apiRouter.use('/admin', adminRouter);
apiRouter.use('/academy-financial-report', academyFinancialReportRouter);
apiRouter.use('/search', searchRouter);
apiRouter.use('/ai-results', aiResultsRouter);
apiRouter.use('/ai-assistant', aiAssistantRouter);
