"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const mongooseMonitor_1 = require("../utils/mongooseMonitor");
(0, mongooseMonitor_1.installMongooseMonitor)();
require("./Advertisement");
require("./AIClassExamInsight");
require("./AIResultInsight");
require("./Announcement");
require("./Attendance");
require("./AttendancePolicy");
require("./AuditLog");
require("./Book");
require("./Branch");
require("./Class");
require("./Course");
require("./Curriculum");
require("./Enrollment");
require("./Exam");
require("./ExamResult");
require("./Expense");
require("./Family");
require("./FamilyLink");
require("./FinanceEntry");
require("./LanguageSetting");
require("./LearningResource");
require("./Message");
require("./Notification");
require("./Owner");
require("./Parent");
require("./Payment");
require("./Permission");
require("./QrContact");
require("./Question");
require("./Report");
require("./Result");
require("./Role");
require("./Salary");
require("./SalaryTransaction");
require("./SessionToken");
require("./StationerySale");
require("./Student");
require("./Subject");
require("./Teacher");
require("./TeacherRating");
require("./User");
