import { installMongooseMonitor } from '../utils/mongooseMonitor';

installMongooseMonitor();

import './Advertisement';
import './AIClassExamInsight';
import './AIResultInsight';
import './Announcement';
import './Attendance';
import './AttendancePolicy';
import './AuditLog';
import './Book';
import './Branch';
import './Class';
import './ContactSetting';
import './Course';
import './Curriculum';
import './Enrollment';
import './Exam';
import './ExamResult';
import './Expense';
import './Faq';
import './Family';
import './FamilyLink';
import './FinanceEntry';
import './LanguageSetting';
import './LegalDocument';
import './LearningResource';
import './Message';
import './Notification';
import './Owner';
import './Parent';
import './Payment';
import './Permission';
import './QrContact';
import './Question';
import './Report';
import './Result';
import './Role';
import './Salary';
import './SalaryTransaction';
import './SessionToken';
import './StationerySale';
import './Student';
import './Subject';
import './Teacher';
import './TeacherRating';
import './User';
